namespace MySql
{
    partial class MainForm
    {
        /// <summary>
        /// Обязательная переменная конструктора.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Освободить все используемые ресурсы.
        /// </summary>
        /// <param name="disposing">истинно, если управляемый ресурс должен быть удален; иначе ложно.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Код, автоматически созданный конструктором форм Windows

        /// <summary>
        /// Требуемый метод для поддержки конструктора — не изменяйте 
        /// содержимое этого метода с помощью редактора кода.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.books_datagrid = new Bunifu.Framework.UI.BunifuCustomDataGrid();
            this.bunifuGradientPanel1 = new Bunifu.Framework.UI.BunifuGradientPanel();
            this.bunifuButton4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuImageButton1 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.name_book = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.progress_bar = new Bunifu.UI.Winforms.BunifuProgressBar();
            this.tv_search = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.bunifuButton5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.remove = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel();
            this.coming_date = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.coming_amount = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.coming_price = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.out_going_amount = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.out_going_date = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.image_book = new Bunifu.UI.WinForms.BunifuImageButton();
            this.backgroundWorker1 = new System.ComponentModel.BackgroundWorker();
            ((System.ComponentModel.ISupportInitialize)(this.books_datagrid)).BeginInit();
            this.bunifuGradientPanel1.SuspendLayout();
            this.bunifuShadowPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // books_datagrid
            // 
            this.books_datagrid.AllowUserToAddRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.Color.White;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.books_datagrid.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.books_datagrid.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.books_datagrid.AutoSizeRowsMode = System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
            this.books_datagrid.BackgroundColor = System.Drawing.Color.White;
            this.books_datagrid.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.books_datagrid.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.RaisedHorizontal;
            this.books_datagrid.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.Silver;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Arial Narrow", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle2.Padding = new System.Windows.Forms.Padding(3, 0, 3, 0);
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.Silver;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.books_datagrid.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.books_datagrid.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.MediumSlateBlue;
            dataGridViewCellStyle3.NullValue = "0";
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.LightGray;
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Silver;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.books_datagrid.DefaultCellStyle = dataGridViewCellStyle3;
            this.books_datagrid.DoubleBuffered = true;
            this.books_datagrid.EditMode = System.Windows.Forms.DataGridViewEditMode.EditProgrammatically;
            this.books_datagrid.EnableHeadersVisualStyles = false;
            this.books_datagrid.GridColor = System.Drawing.Color.Silver;
            this.books_datagrid.HeaderBgColor = System.Drawing.Color.Silver;
            this.books_datagrid.HeaderForeColor = System.Drawing.Color.Black;
            this.books_datagrid.Location = new System.Drawing.Point(0, 379);
            this.books_datagrid.MinimumSize = new System.Drawing.Size(0, 10);
            this.books_datagrid.Name = "books_datagrid";
            this.books_datagrid.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Century Schoolbook", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Silver;
            dataGridViewCellStyle4.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.Color.Silver;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.books_datagrid.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.books_datagrid.RowHeadersVisible = false;
            this.books_datagrid.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.AutoSizeToDisplayedHeaders;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Maiandra GD", 15.15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.Silver;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.Silver;
            this.books_datagrid.RowsDefaultCellStyle = dataGridViewCellStyle5;
            this.books_datagrid.RowTemplate.DefaultCellStyle.ForeColor = System.Drawing.Color.Black;
            this.books_datagrid.RowTemplate.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.Silver;
            this.books_datagrid.RowTemplate.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.books_datagrid.RowTemplate.Height = 10;
            this.books_datagrid.RowTemplate.Resizable = System.Windows.Forms.DataGridViewTriState.False;
            this.books_datagrid.Size = new System.Drawing.Size(1291, 653);
            this.books_datagrid.TabIndex = 9;
            this.books_datagrid.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.bunifuCustomDataGrid1_CellClick);
            this.books_datagrid.CellMouseDoubleClick += new System.Windows.Forms.DataGridViewCellMouseEventHandler(this.books_datagrid_CellMouseDoubleClick);
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.AutoSize = true;
            this.bunifuGradientPanel1.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.White;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuButton4);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuImageButton1);
            this.bunifuGradientPanel1.Controls.Add(this.name_book);
            this.bunifuGradientPanel1.Controls.Add(this.progress_bar);
            this.bunifuGradientPanel1.Controls.Add(this.tv_search);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuButton5);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuButton3);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuButton2);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuButton1);
            this.bunifuGradientPanel1.Controls.Add(this.remove);
            this.bunifuGradientPanel1.Controls.Add(this.books_datagrid);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel1);
            this.bunifuGradientPanel1.Controls.Add(this.image_book);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuGradientPanel1.ForeColor = System.Drawing.Color.MediumSlateBlue;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.White;
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.White;
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.White;
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.White;
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuGradientPanel1.MinimumSize = new System.Drawing.Size(100, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(1294, 618);
            this.bunifuGradientPanel1.TabIndex = 1;
            // 
            // bunifuButton4
            // 
            this.bunifuButton4.AllowToggling = false;
            this.bunifuButton4.AnimationSpeed = 200;
            this.bunifuButton4.AutoGenerateColors = false;
            this.bunifuButton4.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton4.BackgroundImage")));
            this.bunifuButton4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.ButtonText = "Save";
            this.bunifuButton4.ButtonTextMarginLeft = 0;
            this.bunifuButton4.ColorContrastOnClick = 45;
            this.bunifuButton4.ColorContrastOnHover = 45;
            this.bunifuButton4.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton4.CustomizableEdges = borderEdges1;
            this.bunifuButton4.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton4.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton4.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton4.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton4.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuButton4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton4.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton4.IconMarginLeft = 11;
            this.bunifuButton4.IconPadding = 10;
            this.bunifuButton4.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton4.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton4.IdleBorderRadius = 8;
            this.bunifuButton4.IdleBorderThickness = 1;
            this.bunifuButton4.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton4.IdleIconLeftImage = null;
            this.bunifuButton4.IdleIconRightImage = null;
            this.bunifuButton4.IndicateFocus = false;
            this.bunifuButton4.Location = new System.Drawing.Point(881, 256);
            this.bunifuButton4.Name = "bunifuButton4";
            this.bunifuButton4.onHoverState.BorderColor = System.Drawing.Color.MediumSlateBlue;
            this.bunifuButton4.onHoverState.BorderRadius = 8;
            this.bunifuButton4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.onHoverState.BorderThickness = 1;
            this.bunifuButton4.onHoverState.FillColor = System.Drawing.Color.MediumSlateBlue;
            this.bunifuButton4.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.onHoverState.IconLeftImage = null;
            this.bunifuButton4.onHoverState.IconRightImage = null;
            this.bunifuButton4.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton4.OnIdleState.BorderRadius = 8;
            this.bunifuButton4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnIdleState.BorderThickness = 1;
            this.bunifuButton4.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton4.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton4.OnIdleState.IconLeftImage = null;
            this.bunifuButton4.OnIdleState.IconRightImage = null;
            this.bunifuButton4.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton4.OnPressedState.BorderRadius = 8;
            this.bunifuButton4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnPressedState.BorderThickness = 1;
            this.bunifuButton4.OnPressedState.FillColor = System.Drawing.Color.MediumSlateBlue;
            this.bunifuButton4.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.OnPressedState.IconLeftImage = null;
            this.bunifuButton4.OnPressedState.IconRightImage = null;
            this.bunifuButton4.Size = new System.Drawing.Size(150, 55);
            this.bunifuButton4.TabIndex = 54;
            this.bunifuButton4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton4.TextMarginLeft = 0;
            this.bunifuButton4.UseDefaultRadiusAndThickness = true;
            this.bunifuButton4.Click += new System.EventHandler(this.bunifuButton4_Click_1);
            // 
            // bunifuImageButton1
            // 
            this.bunifuImageButton1.ActiveImage = null;
            this.bunifuImageButton1.AllowAnimations = true;
            this.bunifuImageButton1.AllowBuffering = false;
            this.bunifuImageButton1.AllowZooming = true;
            this.bunifuImageButton1.BackColor = System.Drawing.Color.White;
            this.bunifuImageButton1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.ErrorImage")));
            this.bunifuImageButton1.FadeWhenInactive = false;
            this.bunifuImageButton1.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.Image")));
            this.bunifuImageButton1.ImageActive = null;
            this.bunifuImageButton1.ImageLocation = null;
            this.bunifuImageButton1.ImageMargin = 0;
            this.bunifuImageButton1.ImageSize = new System.Drawing.Size(22, 21);
            this.bunifuImageButton1.ImageZoomSize = new System.Drawing.Size(22, 21);
            this.bunifuImageButton1.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.InitialImage")));
            this.bunifuImageButton1.Location = new System.Drawing.Point(284, 30);
            this.bunifuImageButton1.Name = "bunifuImageButton1";
            this.bunifuImageButton1.Rotation = 0;
            this.bunifuImageButton1.ShowActiveImage = true;
            this.bunifuImageButton1.ShowCursorChanges = true;
            this.bunifuImageButton1.ShowImageBorders = true;
            this.bunifuImageButton1.ShowSizeMarkers = false;
            this.bunifuImageButton1.Size = new System.Drawing.Size(22, 21);
            this.bunifuImageButton1.TabIndex = 1;
            this.bunifuImageButton1.ToolTipText = "";
            this.bunifuImageButton1.WaitOnLoad = false;
            this.bunifuImageButton1.Zoom = 0;
            this.bunifuImageButton1.ZoomSpeed = 10;
            // 
            // name_book
            // 
            this.name_book.AcceptsReturn = false;
            this.name_book.AcceptsTab = false;
            this.name_book.AnimationSpeed = 200;
            this.name_book.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.name_book.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.name_book.BackColor = System.Drawing.Color.Transparent;
            this.name_book.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("name_book.BackgroundImage")));
            this.name_book.BorderColorActive = System.Drawing.Color.Black;
            this.name_book.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.name_book.BorderColorHover = System.Drawing.Color.Black;
            this.name_book.BorderColorIdle = System.Drawing.Color.Black;
            this.name_book.BorderRadius = 10;
            this.name_book.BorderThickness = 1;
            this.name_book.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.name_book.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.name_book.DefaultFont = new System.Drawing.Font("Tw Cen MT Condensed Extra Bold", 14.25F);
            this.name_book.DefaultText = "";
            this.name_book.FillColor = System.Drawing.Color.White;
            this.name_book.ForeColor = System.Drawing.Color.DimGray;
            this.name_book.HideSelection = true;
            this.name_book.IconLeft = null;
            this.name_book.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.name_book.IconPadding = 10;
            this.name_book.IconRight = null;
            this.name_book.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.name_book.Lines = new string[0];
            this.name_book.Location = new System.Drawing.Point(376, 21);
            this.name_book.MaxLength = 32767;
            this.name_book.MinimumSize = new System.Drawing.Size(1, 1);
            this.name_book.Modified = false;
            this.name_book.Multiline = false;
            this.name_book.Name = "name_book";
            stateProperties1.BorderColor = System.Drawing.Color.Black;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.name_book.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.name_book.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Black;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.name_book.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Black;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.DimGray;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.name_book.OnIdleState = stateProperties4;
            this.name_book.PasswordChar = '\0';
            this.name_book.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.name_book.PlaceholderText = "Названия";
            this.name_book.ReadOnly = false;
            this.name_book.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.name_book.SelectedText = "";
            this.name_book.SelectionLength = 0;
            this.name_book.SelectionStart = 0;
            this.name_book.ShortcutsEnabled = true;
            this.name_book.Size = new System.Drawing.Size(378, 42);
            this.name_book.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.name_book.TabIndex = 33;
            this.name_book.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.name_book.TextMarginBottom = 0;
            this.name_book.TextMarginLeft = 5;
            this.name_book.TextMarginTop = 0;
            this.name_book.TextPlaceholder = "Названия";
            this.name_book.UseSystemPasswordChar = false;
            this.name_book.WordWrap = true;
            this.name_book.KeyDown += new System.Windows.Forms.KeyEventHandler(this.name_book_KeyDown);
            // 
            // progress_bar
            // 
            this.progress_bar.Animation = 0;
            this.progress_bar.AnimationStep = 10;
            this.progress_bar.BackColor = System.Drawing.Color.Silver;
            this.progress_bar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("progress_bar.BackgroundImage")));
            this.progress_bar.BorderColor = System.Drawing.Color.Silver;
            this.progress_bar.BorderRadius = 1;
            this.progress_bar.BorderThickness = 1;
            this.progress_bar.Location = new System.Drawing.Point(0, 379);
            this.progress_bar.MaximumValue = 100;
            this.progress_bar.MinimumValue = 0;
            this.progress_bar.Name = "progress_bar";
            this.progress_bar.ProgressBackColor = System.Drawing.Color.White;
            this.progress_bar.ProgressColorLeft = System.Drawing.Color.MediumSlateBlue;
            this.progress_bar.ProgressColorRight = System.Drawing.Color.MediumSlateBlue;
            this.progress_bar.Size = new System.Drawing.Size(1291, 28);
            this.progress_bar.TabIndex = 53;
            this.progress_bar.Value = 50;
            this.progress_bar.Visible = false;
            // 
            // tv_search
            // 
            this.tv_search.AcceptsReturn = false;
            this.tv_search.AcceptsTab = false;
            this.tv_search.AnimationSpeed = 200;
            this.tv_search.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tv_search.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tv_search.BackColor = System.Drawing.Color.Transparent;
            this.tv_search.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tv_search.BackgroundImage")));
            this.tv_search.BorderColorActive = System.Drawing.Color.White;
            this.tv_search.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.tv_search.BorderColorHover = System.Drawing.Color.White;
            this.tv_search.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.tv_search.BorderRadius = 5;
            this.tv_search.BorderThickness = 0;
            this.tv_search.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tv_search.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tv_search.DefaultFont = new System.Drawing.Font("Tw Cen MT Condensed Extra Bold", 14.25F);
            this.tv_search.DefaultText = "";
            this.tv_search.FillColor = System.Drawing.Color.White;
            this.tv_search.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.tv_search.HideSelection = true;
            this.tv_search.IconLeft = null;
            this.tv_search.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tv_search.IconPadding = 10;
            this.tv_search.IconRight = null;
            this.tv_search.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tv_search.Lines = new string[0];
            this.tv_search.Location = new System.Drawing.Point(40, 25);
            this.tv_search.MaxLength = 32767;
            this.tv_search.MinimumSize = new System.Drawing.Size(1, 1);
            this.tv_search.Modified = false;
            this.tv_search.Multiline = false;
            this.tv_search.Name = "tv_search";
            stateProperties5.BorderColor = System.Drawing.Color.Black;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tv_search.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tv_search.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.White;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tv_search.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tv_search.OnIdleState = stateProperties8;
            this.tv_search.PasswordChar = '\0';
            this.tv_search.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.tv_search.PlaceholderText = "Qidirish";
            this.tv_search.ReadOnly = false;
            this.tv_search.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tv_search.SelectedText = "";
            this.tv_search.SelectionLength = 0;
            this.tv_search.SelectionStart = 0;
            this.tv_search.ShortcutsEnabled = true;
            this.tv_search.Size = new System.Drawing.Size(227, 32);
            this.tv_search.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.tv_search.TabIndex = 43;
            this.tv_search.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.tv_search.TextMarginBottom = 0;
            this.tv_search.TextMarginLeft = 5;
            this.tv_search.TextMarginTop = 0;
            this.tv_search.TextPlaceholder = "Qidirish";
            this.tv_search.UseSystemPasswordChar = false;
            this.tv_search.WordWrap = true;
            this.tv_search.KeyDown += new System.Windows.Forms.KeyEventHandler(this.tv_search_KeyDown);
            // 
            // bunifuButton5
            // 
            this.bunifuButton5.AllowToggling = false;
            this.bunifuButton5.AnimationSpeed = 200;
            this.bunifuButton5.AutoGenerateColors = false;
            this.bunifuButton5.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton5.BackColor1 = System.Drawing.SystemColors.Window;
            this.bunifuButton5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton5.BackgroundImage")));
            this.bunifuButton5.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton5.ButtonText = "EXCEL";
            this.bunifuButton5.ButtonTextMarginLeft = 0;
            this.bunifuButton5.ColorContrastOnClick = 45;
            this.bunifuButton5.ColorContrastOnHover = 45;
            this.bunifuButton5.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton5.CustomizableEdges = borderEdges2;
            this.bunifuButton5.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton5.DisabledBorderColor = System.Drawing.Color.Silver;
            this.bunifuButton5.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton5.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton5.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton5.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuButton5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton5.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton5.IconMarginLeft = 11;
            this.bunifuButton5.IconPadding = 10;
            this.bunifuButton5.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton5.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton5.IdleBorderRadius = 8;
            this.bunifuButton5.IdleBorderThickness = 1;
            this.bunifuButton5.IdleFillColor = System.Drawing.SystemColors.Window;
            this.bunifuButton5.IdleIconLeftImage = null;
            this.bunifuButton5.IdleIconRightImage = null;
            this.bunifuButton5.IndicateFocus = false;
            this.bunifuButton5.Location = new System.Drawing.Point(1077, 146);
            this.bunifuButton5.Name = "bunifuButton5";
            this.bunifuButton5.onHoverState.BorderColor = System.Drawing.Color.ForestGreen;
            this.bunifuButton5.onHoverState.BorderRadius = 8;
            this.bunifuButton5.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton5.onHoverState.BorderThickness = 1;
            this.bunifuButton5.onHoverState.FillColor = System.Drawing.Color.ForestGreen;
            this.bunifuButton5.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton5.onHoverState.IconLeftImage = null;
            this.bunifuButton5.onHoverState.IconRightImage = null;
            this.bunifuButton5.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton5.OnIdleState.BorderRadius = 8;
            this.bunifuButton5.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton5.OnIdleState.BorderThickness = 1;
            this.bunifuButton5.OnIdleState.FillColor = System.Drawing.SystemColors.Window;
            this.bunifuButton5.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton5.OnIdleState.IconLeftImage = null;
            this.bunifuButton5.OnIdleState.IconRightImage = null;
            this.bunifuButton5.OnPressedState.BorderColor = System.Drawing.Color.ForestGreen;
            this.bunifuButton5.OnPressedState.BorderRadius = 8;
            this.bunifuButton5.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton5.OnPressedState.BorderThickness = 1;
            this.bunifuButton5.OnPressedState.FillColor = System.Drawing.Color.ForestGreen;
            this.bunifuButton5.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton5.OnPressedState.IconLeftImage = null;
            this.bunifuButton5.OnPressedState.IconRightImage = null;
            this.bunifuButton5.Size = new System.Drawing.Size(150, 55);
            this.bunifuButton5.TabIndex = 51;
            this.bunifuButton5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton5.TextMarginLeft = 0;
            this.bunifuButton5.UseDefaultRadiusAndThickness = true;
            this.bunifuButton5.Click += new System.EventHandler(this.bunifuButton5_Click);
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "Refresh";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges3;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuButton3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton3.IdleBorderRadius = 5;
            this.bunifuButton3.IdleBorderThickness = 1;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton3.IdleIconLeftImage = null;
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(881, 40);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.MediumSlateBlue;
            this.bunifuButton3.onHoverState.BorderRadius = 5;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.MediumSlateBlue;
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton3.OnIdleState.BorderRadius = 5;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton3.OnIdleState.IconLeftImage = null;
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton3.OnPressedState.BorderRadius = 5;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.MediumSlateBlue;
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(150, 56);
            this.bunifuButton3.TabIndex = 46;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            this.bunifuButton3.Click += new System.EventHandler(this.bunifuButton3_Click);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "New";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges4;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuButton2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton2.IdleBorderRadius = 8;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(881, 146);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.MediumSlateBlue;
            this.bunifuButton2.onHoverState.BorderRadius = 8;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.MediumSlateBlue;
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton2.OnIdleState.BorderRadius = 8;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.BorderRadius = 8;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.MediumSlateBlue;
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(150, 55);
            this.bunifuButton2.TabIndex = 44;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Exit";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges5;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuButton1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton1.IdleBorderRadius = 8;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(1077, 256);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.DarkViolet;
            this.bunifuButton1.onHoverState.BorderRadius = 8;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.DarkViolet;
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton1.OnIdleState.BorderRadius = 8;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.BorderRadius = 8;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.DarkViolet;
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(150, 55);
            this.bunifuButton1.TabIndex = 43;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click_1);
            // 
            // remove
            // 
            this.remove.AllowToggling = false;
            this.remove.AnimationSpeed = 200;
            this.remove.AutoGenerateColors = false;
            this.remove.BackColor = System.Drawing.Color.Transparent;
            this.remove.BackColor1 = System.Drawing.Color.White;
            this.remove.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("remove.BackgroundImage")));
            this.remove.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.remove.ButtonText = "O\'chirish";
            this.remove.ButtonTextMarginLeft = 0;
            this.remove.ColorContrastOnClick = 45;
            this.remove.ColorContrastOnHover = 45;
            this.remove.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.remove.CustomizableEdges = borderEdges6;
            this.remove.DialogResult = System.Windows.Forms.DialogResult.None;
            this.remove.DisabledBorderColor = System.Drawing.Color.Empty;
            this.remove.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.remove.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.remove.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.remove.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.remove.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.remove.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.remove.IconMarginLeft = 11;
            this.remove.IconPadding = 10;
            this.remove.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.remove.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.remove.IdleBorderRadius = 8;
            this.remove.IdleBorderThickness = 1;
            this.remove.IdleFillColor = System.Drawing.Color.White;
            this.remove.IdleIconLeftImage = null;
            this.remove.IdleIconRightImage = null;
            this.remove.IndicateFocus = false;
            this.remove.Location = new System.Drawing.Point(1077, 41);
            this.remove.Name = "remove";
            this.remove.onHoverState.BorderColor = System.Drawing.Color.MediumSlateBlue;
            this.remove.onHoverState.BorderRadius = 8;
            this.remove.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.remove.onHoverState.BorderThickness = 1;
            this.remove.onHoverState.FillColor = System.Drawing.Color.MediumSlateBlue;
            this.remove.onHoverState.ForeColor = System.Drawing.Color.White;
            this.remove.onHoverState.IconLeftImage = null;
            this.remove.onHoverState.IconRightImage = null;
            this.remove.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.remove.OnIdleState.BorderRadius = 8;
            this.remove.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.remove.OnIdleState.BorderThickness = 1;
            this.remove.OnIdleState.FillColor = System.Drawing.Color.White;
            this.remove.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.remove.OnIdleState.IconLeftImage = null;
            this.remove.OnIdleState.IconRightImage = null;
            this.remove.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.remove.OnPressedState.BorderRadius = 8;
            this.remove.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.remove.OnPressedState.BorderThickness = 1;
            this.remove.OnPressedState.FillColor = System.Drawing.Color.MediumSlateBlue;
            this.remove.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.remove.OnPressedState.IconLeftImage = null;
            this.remove.OnPressedState.IconRightImage = null;
            this.remove.Size = new System.Drawing.Size(150, 55);
            this.remove.TabIndex = 29;
            this.remove.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.remove.TextMarginLeft = 0;
            this.remove.UseDefaultRadiusAndThickness = true;
            this.remove.Click += new System.EventHandler(this.remove_Click);
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.Gainsboro;
            this.bunifuShadowPanel1.Controls.Add(this.coming_date);
            this.bunifuShadowPanel1.Controls.Add(this.coming_amount);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuShadowPanel1.Controls.Add(this.coming_price);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel1.Controls.Add(this.out_going_amount);
            this.bunifuShadowPanel1.Controls.Add(this.out_going_date);
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(336, 76);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.Empty;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(469, 262);
            this.bunifuShadowPanel1.TabIndex = 47;
            // 
            // coming_date
            // 
            this.coming_date.BorderRadius = 5;
            this.coming_date.CalendarForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.coming_date.CalendarTitleBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.coming_date.CalendarTitleForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.coming_date.CalendarTrailingForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.coming_date.Color = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.coming_date.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thick;
            this.coming_date.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.coming_date.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.coming_date.DisplayWeekNumbers = false;
            this.coming_date.DPHeight = 0;
            this.coming_date.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.coming_date.FillDatePicker = false;
            this.coming_date.ForeColor = System.Drawing.Color.Black;
            this.coming_date.Icon = ((System.Drawing.Image)(resources.GetObject("coming_date.Icon")));
            this.coming_date.IconColor = System.Drawing.Color.Black;
            this.coming_date.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.coming_date.Location = new System.Drawing.Point(6, 187);
            this.coming_date.MinimumSize = new System.Drawing.Size(162, 32);
            this.coming_date.Name = "coming_date";
            this.coming_date.Size = new System.Drawing.Size(162, 32);
            this.coming_date.TabIndex = 36;
            // 
            // coming_amount
            // 
            this.coming_amount.AcceptsReturn = false;
            this.coming_amount.AcceptsTab = false;
            this.coming_amount.AnimationSpeed = 200;
            this.coming_amount.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.coming_amount.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.coming_amount.AutoSize = true;
            this.coming_amount.BackColor = System.Drawing.Color.Transparent;
            this.coming_amount.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("coming_amount.BackgroundImage")));
            this.coming_amount.BorderColorActive = System.Drawing.Color.SlateGray;
            this.coming_amount.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.coming_amount.BorderColorHover = System.Drawing.Color.Black;
            this.coming_amount.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.coming_amount.BorderRadius = 8;
            this.coming_amount.BorderThickness = 1;
            this.coming_amount.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.coming_amount.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.coming_amount.DefaultFont = new System.Drawing.Font("Consolas", 14.25F);
            this.coming_amount.DefaultText = "";
            this.coming_amount.FillColor = System.Drawing.Color.White;
            this.coming_amount.ForeColor = System.Drawing.Color.DimGray;
            this.coming_amount.HideSelection = true;
            this.coming_amount.IconLeft = null;
            this.coming_amount.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.coming_amount.IconPadding = 10;
            this.coming_amount.IconRight = null;
            this.coming_amount.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.coming_amount.Lines = new string[0];
            this.coming_amount.Location = new System.Drawing.Point(6, 70);
            this.coming_amount.MaxLength = 32767;
            this.coming_amount.MinimumSize = new System.Drawing.Size(1, 1);
            this.coming_amount.Modified = false;
            this.coming_amount.Multiline = false;
            this.coming_amount.Name = "coming_amount";
            stateProperties9.BorderColor = System.Drawing.Color.SlateGray;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.coming_amount.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.coming_amount.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Black;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.coming_amount.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.DimGray;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.coming_amount.OnIdleState = stateProperties12;
            this.coming_amount.PasswordChar = '\0';
            this.coming_amount.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.coming_amount.PlaceholderText = "ШТ";
            this.coming_amount.ReadOnly = false;
            this.coming_amount.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.coming_amount.SelectedText = "";
            this.coming_amount.SelectionLength = 0;
            this.coming_amount.SelectionStart = 0;
            this.coming_amount.ShortcutsEnabled = true;
            this.coming_amount.Size = new System.Drawing.Size(162, 32);
            this.coming_amount.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.coming_amount.TabIndex = 32;
            this.coming_amount.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.coming_amount.TextMarginBottom = 0;
            this.coming_amount.TextMarginLeft = 5;
            this.coming_amount.TextMarginTop = 0;
            this.coming_amount.TextPlaceholder = "ШТ";
            this.coming_amount.UseSystemPasswordChar = false;
            this.coming_amount.WordWrap = true;
            this.coming_amount.KeyDown += new System.Windows.Forms.KeyEventHandler(this.coming_amount_KeyDown);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Trebuchet MS", 18F);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuLabel2.Location = new System.Drawing.Point(271, 19);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(77, 31);
            this.bunifuLabel2.TabIndex = 42;
            this.bunifuLabel2.Text = "Chiqim";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // coming_price
            // 
            this.coming_price.AcceptsReturn = false;
            this.coming_price.AcceptsTab = false;
            this.coming_price.AnimationSpeed = 200;
            this.coming_price.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.coming_price.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.coming_price.BackColor = System.Drawing.Color.Transparent;
            this.coming_price.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("coming_price.BackgroundImage")));
            this.coming_price.BorderColorActive = System.Drawing.Color.SlateGray;
            this.coming_price.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.coming_price.BorderColorHover = System.Drawing.Color.Black;
            this.coming_price.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.coming_price.BorderRadius = 8;
            this.coming_price.BorderThickness = 1;
            this.coming_price.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.coming_price.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.coming_price.DefaultFont = new System.Drawing.Font("Consolas", 14.25F);
            this.coming_price.DefaultText = "";
            this.coming_price.FillColor = System.Drawing.Color.White;
            this.coming_price.ForeColor = System.Drawing.Color.DimGray;
            this.coming_price.HideSelection = true;
            this.coming_price.IconLeft = null;
            this.coming_price.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.coming_price.IconPadding = 10;
            this.coming_price.IconRight = null;
            this.coming_price.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.coming_price.Lines = new string[0];
            this.coming_price.Location = new System.Drawing.Point(6, 131);
            this.coming_price.MaxLength = 32767;
            this.coming_price.MinimumSize = new System.Drawing.Size(1, 1);
            this.coming_price.Modified = false;
            this.coming_price.Multiline = false;
            this.coming_price.Name = "coming_price";
            stateProperties13.BorderColor = System.Drawing.Color.SlateGray;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.coming_price.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.coming_price.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Black;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.coming_price.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.DimGray;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.coming_price.OnIdleState = stateProperties16;
            this.coming_price.PasswordChar = '\0';
            this.coming_price.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.coming_price.PlaceholderText = "Цена";
            this.coming_price.ReadOnly = false;
            this.coming_price.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.coming_price.SelectedText = "";
            this.coming_price.SelectionLength = 0;
            this.coming_price.SelectionStart = 0;
            this.coming_price.ShortcutsEnabled = true;
            this.coming_price.Size = new System.Drawing.Size(162, 32);
            this.coming_price.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.coming_price.TabIndex = 31;
            this.coming_price.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.coming_price.TextMarginBottom = 0;
            this.coming_price.TextMarginLeft = 5;
            this.coming_price.TextMarginTop = 0;
            this.coming_price.TextPlaceholder = "Цена";
            this.coming_price.UseSystemPasswordChar = false;
            this.coming_price.WordWrap = true;
            this.coming_price.KeyDown += new System.Windows.Forms.KeyEventHandler(this.coming_price_KeyDown);
            this.coming_price.KeyUp += new System.Windows.Forms.KeyEventHandler(this.coming_price_KeyUp);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Verdana", 18F);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(36, 19);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(65, 31);
            this.bunifuLabel1.TabIndex = 42;
            this.bunifuLabel1.Text = "Kirim";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // out_going_amount
            // 
            this.out_going_amount.AcceptsReturn = false;
            this.out_going_amount.AcceptsTab = false;
            this.out_going_amount.AnimationSpeed = 200;
            this.out_going_amount.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.out_going_amount.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.out_going_amount.AutoSize = true;
            this.out_going_amount.BackColor = System.Drawing.Color.Transparent;
            this.out_going_amount.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("out_going_amount.BackgroundImage")));
            this.out_going_amount.BorderColorActive = System.Drawing.Color.Gray;
            this.out_going_amount.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.out_going_amount.BorderColorHover = System.Drawing.Color.Black;
            this.out_going_amount.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.out_going_amount.BorderRadius = 8;
            this.out_going_amount.BorderThickness = 1;
            this.out_going_amount.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.out_going_amount.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.out_going_amount.DefaultFont = new System.Drawing.Font("Consolas", 14.25F);
            this.out_going_amount.DefaultText = "";
            this.out_going_amount.FillColor = System.Drawing.Color.White;
            this.out_going_amount.ForeColor = System.Drawing.Color.DimGray;
            this.out_going_amount.HideSelection = true;
            this.out_going_amount.IconLeft = null;
            this.out_going_amount.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.out_going_amount.IconPadding = 10;
            this.out_going_amount.IconRight = null;
            this.out_going_amount.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.out_going_amount.Lines = new string[0];
            this.out_going_amount.Location = new System.Drawing.Point(235, 70);
            this.out_going_amount.MaxLength = 32767;
            this.out_going_amount.MinimumSize = new System.Drawing.Size(1, 1);
            this.out_going_amount.Modified = false;
            this.out_going_amount.Multiline = false;
            this.out_going_amount.Name = "out_going_amount";
            stateProperties17.BorderColor = System.Drawing.Color.Gray;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.out_going_amount.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.out_going_amount.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Black;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.out_going_amount.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.DimGray;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.out_going_amount.OnIdleState = stateProperties20;
            this.out_going_amount.Padding = new System.Windows.Forms.Padding(10);
            this.out_going_amount.PasswordChar = '\0';
            this.out_going_amount.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.out_going_amount.PlaceholderText = "ШТ";
            this.out_going_amount.ReadOnly = false;
            this.out_going_amount.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.out_going_amount.SelectedText = "";
            this.out_going_amount.SelectionLength = 0;
            this.out_going_amount.SelectionStart = 0;
            this.out_going_amount.ShortcutsEnabled = true;
            this.out_going_amount.Size = new System.Drawing.Size(162, 32);
            this.out_going_amount.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.out_going_amount.TabIndex = 38;
            this.out_going_amount.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.out_going_amount.TextMarginBottom = 0;
            this.out_going_amount.TextMarginLeft = 10;
            this.out_going_amount.TextMarginTop = 0;
            this.out_going_amount.TextPlaceholder = "ШТ";
            this.out_going_amount.UseSystemPasswordChar = false;
            this.out_going_amount.WordWrap = true;
            this.out_going_amount.KeyDown += new System.Windows.Forms.KeyEventHandler(this.out_going_amount_KeyDown);
            // 
            // out_going_date
            // 
            this.out_going_date.BorderRadius = 5;
            this.out_going_date.CalendarForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.out_going_date.CalendarMonthBackground = System.Drawing.Color.Silver;
            this.out_going_date.CalendarTitleBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.out_going_date.CalendarTitleForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.out_going_date.CalendarTrailingForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.out_going_date.Color = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.out_going_date.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thick;
            this.out_going_date.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.out_going_date.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.out_going_date.DisplayWeekNumbers = false;
            this.out_going_date.DPHeight = 0;
            this.out_going_date.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.out_going_date.FillDatePicker = false;
            this.out_going_date.ForeColor = System.Drawing.Color.Black;
            this.out_going_date.Icon = ((System.Drawing.Image)(resources.GetObject("out_going_date.Icon")));
            this.out_going_date.IconColor = System.Drawing.Color.Black;
            this.out_going_date.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.out_going_date.Location = new System.Drawing.Point(235, 187);
            this.out_going_date.MinimumSize = new System.Drawing.Size(162, 31);
            this.out_going_date.Name = "out_going_date";
            this.out_going_date.Size = new System.Drawing.Size(162, 31);
            this.out_going_date.TabIndex = 41;
            // 
            // image_book
            // 
            this.image_book.ActiveImage = null;
            this.image_book.AllowAnimations = true;
            this.image_book.AllowBuffering = false;
            this.image_book.AllowZooming = true;
            this.image_book.BackColor = System.Drawing.Color.Transparent;
            this.image_book.ErrorImage = ((System.Drawing.Image)(resources.GetObject("image_book.ErrorImage")));
            this.image_book.FadeWhenInactive = false;
            this.image_book.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.image_book.Image = ((System.Drawing.Image)(resources.GetObject("image_book.Image")));
            this.image_book.ImageActive = null;
            this.image_book.ImageLocation = null;
            this.image_book.ImageMargin = 40;
            this.image_book.ImageSize = new System.Drawing.Size(231, 206);
            this.image_book.ImageZoomSize = new System.Drawing.Size(271, 246);
            this.image_book.InitialImage = ((System.Drawing.Image)(resources.GetObject("image_book.InitialImage")));
            this.image_book.Location = new System.Drawing.Point(25, 76);
            this.image_book.Name = "image_book";
            this.image_book.Rotation = 0;
            this.image_book.ShowActiveImage = true;
            this.image_book.ShowCursorChanges = true;
            this.image_book.ShowImageBorders = true;
            this.image_book.ShowSizeMarkers = false;
            this.image_book.Size = new System.Drawing.Size(271, 246);
            this.image_book.TabIndex = 35;
            this.image_book.ToolTipText = "";
            this.image_book.WaitOnLoad = false;
            this.image_book.Zoom = 40;
            this.image_book.ZoomSpeed = 10;
            this.image_book.Click += new System.EventHandler(this.image_book_Click);
            // 
            // backgroundWorker1
            // 
            this.backgroundWorker1.WorkerReportsProgress = true;
            this.backgroundWorker1.WorkerSupportsCancellation = true;
            this.backgroundWorker1.DoWork += new System.ComponentModel.DoWorkEventHandler(this.backgroundWorker1_DoWork);
            this.backgroundWorker1.ProgressChanged += new System.ComponentModel.ProgressChangedEventHandler(this.backgroundWorker1_ProgressChanged);
            this.backgroundWorker1.RunWorkerCompleted += new System.ComponentModel.RunWorkerCompletedEventHandler(this.backgroundWorker1_RunWorkerCompleted);
            // 
            // MainForm
            // 
            this.AccessibleRole = System.Windows.Forms.AccessibleRole.None;
            this.AllowDrop = true;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.MenuHighlight;
            this.ClientSize = new System.Drawing.Size(1294, 618);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Cursor = System.Windows.Forms.Cursors.AppStarting;
            this.ForeColor = System.Drawing.Color.Transparent;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.ImeMode = System.Windows.Forms.ImeMode.Hiragana;
            this.IsMdiContainer = true;
            this.KeyPreview = true;
            this.Name = "MainForm";
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "STORE18";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.MainForm_FormClosing);
            this.Load += new System.EventHandler(this.Form1_Load);
            this.Shown += new System.EventHandler(this.MainForm_Shown);
            ((System.ComponentModel.ISupportInitialize)(this.books_datagrid)).EndInit();
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.Framework.UI.BunifuCustomDataGrid books_datagrid;
        private Bunifu.Framework.UI.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuDatePicker coming_date;
        private Bunifu.UI.WinForms.BunifuImageButton image_book;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox coming_price;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox coming_amount;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox name_book;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton remove;
        private Bunifu.UI.WinForms.BunifuDatePicker out_going_date;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox out_going_amount;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton5;
        public System.ComponentModel.BackgroundWorker backgroundWorker1;
        private Bunifu.UI.Winforms.BunifuProgressBar progress_bar;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox tv_search;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton4;
    }
}

